version: '3.5'
services:
  atuin:
    restart: always
    image: ghcr.io/jevinskie/atuin:latest-jev
    command: server start
    volumes:
      - ./config:/config
    links:
      - postgresql:db
    env_file:
        - .env
    ports:
      - ${ATUIN_PORT}:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
  postgresql:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/postgresql/data/"
    env_file:
        - .env
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
  backup:
      container_name: atuin_db_dumper
      image: prodrigestivill/postgres-backup-local:16-alpine
      env_file:
        - .env
      environment:
        POSTGRES_HOST: postgresql
        POSTGRES_DB: ${ATUIN_DB_NAME}
        POSTGRES_USER: ${ATUIN_DB_USERNAME}
        POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
        SCHEDULE: "@daily"
        BACKUP_DIR: /db_dumps
      volumes:
        - ./db_dumps:/db_dumps
      depends_on:
        - postgresql

